### ISSUE TITLE
Support short test summary info

### ISSUE THREAD

**Issue by davidak** [wimglenn/pytest-custom-report#2]
Thanks for providing this plugin!

Would it be possible to also support changing the characters in the short test summary info?

Currently it is not changed:

![screenshot from 2019-01-22 15-56-39](https://user-images.githubusercontent.com/91113/51543653-5860aa80-1e5e-11e9-8e5f-317fb33271fe.png)

Startet with:

`pytest.main(['-v', '--tb=short', '-rap', '--report-passed=✔', '--report-passed-verbose=✔', '--report-failed=✘', '--report-failed-verbose=✘'])`

**Comment by wimglenn** [comment]
Hmm, this might have to be addressed in `pytest` directly.  My plugin sets the return value of the [`pytest_report_teststatus` hook](https://docs.pytest.org/en/latest/reference.html#_pytest.hookspec.pytest_report_teststatus), but the short test summary info section is not using the hook - instead it just hardcodes some strings. We can monkeypatch but I'd rather not.

On the plus side, if that's fixed in `pytest` then this plugin will just start doing the right thing with no code changes or release necessary.

**Comment by davidak** [comment]
Thanks for the feedback! I will ask them.

**Comment by davidak** [comment]
I see you already created an issue there and multiple pull requests. https://github.com/pytest-dev/pytest/issues/4667

Perfect. Thank you very much!

**Comment by wimglenn** [comment]
@davidak   This seems fixed in pytest v4.2.0 released just now. FYI.

**Comment by davidak** [comment]
Amazing. Thank you very much!

**Comment by davidak** [comment]
I can confirm that it works.

![screenshot from 2019-01-31 15-12-09](https://user-images.githubusercontent.com/91113/52059695-ca29aa00-256a-11e9-891f-da0a1501441b.png)
