### ISSUE TITLE
Support usage of docstring as test name

### ISSUE THREAD

**Issue by davidak** [wimglenn/pytest-custom-report#6]
Would you accept a PR that adds support for optional usage of the docstring as test name?

I think such a feature would fit a plugin named "pytest-custom-report".

There is some demand for such a feature: https://stackoverflow.com/questions/28898919/use-docstrings-to-list-tests-in-py-test

And the pytest developers don't want to include it (yet): https://github.com/pytest-dev/pytest/issues/4701

**Comment by wimglenn** [comment]
You might also consider to put it in an entirely separate plugin: since this one only really concerns the `pytest_report_teststatus` hook, there is not going to be much (or any) overlap in the implementation.

But, if this can be done cleanly and correctly (only using the public APIs of pytest, cross-compat + tests), I would consider merging it - or, at least, code reviewing it.
